export default {
  home: 'Domov',
  about: 'O nás',
  registration: 'Registrace',
  login: 'Přihlášení',
  courses: 'Kurzy',
  coursesOffered: 'Nabídka kurzů',
  noCoursesAvailable: 'It seems that there are currently no courses on offer.',
  signUpToCourse: 'Sign up',
  capacity: 'Kapacita',
  languageLevel: 'Úroveň',
  enrollInCourse: 'Enroll',
  cancelEnrollment: 'Cancel enrollment',
  courseFull: 'Course is full',
  teacher: 'Teacher',
};
