export default {
  home: 'Domov',
  about: 'O nás',
  registration: 'Registrace',
  login: 'Přihlášení',
  logout: 'Odhlášení',
  courses: 'Kurzy',
  coursesOffered: 'Nabídka kurzů',
  noCoursesAvailable: 'Zdá se, že aktuálně nejsou v nabídce žádné kurzy.',
  signUpToCourse: 'Sign up',
  capacity: 'Kapacita',
  languageLevel: 'Úroveň',
  enrollInCourse: 'Zapsat se',
  cancelEnrollment: 'Zrušit zápis',
  courseFull: 'Kurz je plně obsazený',
  teacher: 'Učitel',
  addNewCourse: 'Přidat nový kurz',
  courseName: 'Název kurzu',
  courseDescription: 'Popis kurzu',
  courseLanguage: 'Jazyk kurzu',
  price: 'Cena',
  myCourses: 'Moje kurzy',
  noUserCourses: 'Nejste zapsán v žádném kurzu',
  groupChat: 'Skupinový chat',
  profilePicture: 'Profilový obrázek',
  profile: 'Profil',
  registration_failure: 'Registrace se nezdařila.',
  registration_success_title: 'Úspěšná registrace!',
  registration_success_msg: 'Registrace proběhla úspěšně.',
  login_failure: 'Přihlášení se nezdařilo.',
  login_success: 'přihlášení bylo úspěšné',
  first_name_field_required: 'Pole křestního jména je povinné',
  last_name_field_required: 'Pole příjmení je povinné',
  email_field_required: 'Pole pro email je povinné',
  password_field_required: 'Pole pre heslo je povinné',
  invalid_email_format: 'Invalid email format',
  invalid_length_password: 'Heslo musí mít alespoň 8 znaků',
  passwords_must_match: 'Hesla se musí shodovat',
  no_account_yet: 'Ještě nemáte účet?',
  register_yourself: 'Zaregistrujte se!',
  or_uppercase: 'NEBO',
  sign_in_with: 'Přihlásit se přes ',
  register_for_language_school: 'Zaregistrujte se do jazykové školy!',
  take_language_skills_to_next_level:
    'A posuňte své jazykové znalosti na novou úroveň!',
  reset: 'Resetovat',
  already_have_account: 'Už máte účet?',
  login_yourself: 'Přihlaste se!',
  welcome_home_screen: 'Vítejte na domovské stránce aplikace LangIS!',
  home_screen_msg:
    'Z nabídky výše si vyberte aktuální nabídku kurzů nebo si prohlédněte vaše aktuálně zaregistrované kurzy.',
  are_you_sure: 'Jsi si jisti?',
  replace_profile_picture:
    'Opravdu chcete změnit vaši profilovou fotku za vybranou fotku?',
  submit: 'Potvrdit',
  profile_picture_change_success:
    'Profilová fotka byla úspěšně změněna! Pro zobrazení změn je nutné refreshnout stránku!',
  profile_picture_change_failure:
    'Uploading of your profile picture has failed!',
  not_listed: 'Neuvedeno',
  information: 'Informace: ',
  email: 'Email: ',
  role: 'Role: ',
  age: 'Stáří: ',
  location: 'Lokace: ',
  page_not_found: 'Stránka nenalezena!',
  page_not_found_msg:
    'Stránka, kterou hledáte, mohla být odstraněna, její název se změnil nebo je dočasně nedostupná.',
  go_to_homepage: 'Přejít na domovskou stránku',
  enter_your_email: 'Zadejte svůj e-mail...',
  password: 'Heslo: ',
  enter_your_password: 'Zadejte své heslo...',
  first_name: 'křestní jméno: ',
  enter_your_first_name: 'Zadejte své křestní jméno...',
  last_name: 'Příjmení: ',
  enter_your_last_name: 'Zadejte své příjmení...',
  confirm_password: 'Potvrzení hesla: ',
  enter_your_confirmation_password: 'Zadejte své heslo znovu...',
  beginner: 'Úplní začátečníci',
  elemenatary: 'Začátečníci',
  preIntermediate: 'Mírně pokročilí',
  intermediate: 'Středně pokročilí',
  upperIntermediate: 'Výše pokročilí',
  advanced: 'Pokročilí',
  english: 'Angličtina',
  spanish: 'Španělština',
  italian: 'Italština',
  german: 'Němčina',
  french: 'Francouzština',
  moreInfo: 'More info',
  courseDetail: 'Detail kurzu',
  courseAddedSuccessfullyTitle: 'Kurz vytvořen!',
  courseAddedSuccessfullyMsg: 'Nový kurz byl úspěšně přidán.',
  courseAddedFailed: 'Chyba - kurz nebyl přidán!',
  edit: 'Upravit',
  delete: 'Smazat',
  noLessonsAvailable: 'Tento kurz nemá aktuálně žádné lekce',
  lesson: 'Lekce',
  minutes: 'minut',
  classroom: 'Učebna',
  lessonContent: 'Náplň lekce',
  averageRating: 'Průměrné hodnocení',
  noRating: 'Zatím nehodnoceno',
  addNewLesson: 'Přidat novou lekci',
  rateThisCourse: 'Ohodnoťte tento kurz!',
  cancel: 'Zrušit',
  rate: 'Ohodnotit!',
  lessonLengthInMinutes: 'Délka v minutách',
  lessonDateAndTime: 'Datum a čas',
  deleteLesson: 'Smazat lekci',
  deleteFile: 'Smazt soubor',
  uploadFile: 'Nahrát soubor',
  fileIsRequired: 'Soubor je povinný!',
};
