export default {
  home: 'Domov',
  about: 'O nás',
  registration: 'Registrace',
  login: 'Přihlášení',
  courses: 'Kurzy',
  coursesOffered: 'Nabídka kurzů',
  noCoursesAvailable: 'It seems that there are currently no courses on offer.',
  signUpToCourse: 'Sign up',
  capacity: 'Kapacita',
  languageLevel: 'Úroveň',
  enrollInCourse: 'Zapsat se',
  cancelEnrollment: 'Zrušit zápis',
  courseFull: 'Kurz je plně obsazený',
  teacher: 'Učitel',
  addNewCourse: 'Přidat nový kurz',
  courseName: 'Název kurzu',
  courseDescription: 'Course description',
  courseLanguage: 'Course language',
  price: 'Price',
  myCourses: 'Moje kurzy',
  noUserCourses: 'Nejste zapsán v žádném kurzu',
  groupChat: 'Skupinový chat',
  profilePicture: 'Profile picture',
};
