export default {
  home: 'Home',
  about: 'About',
  registration: 'Sign up',
  login: 'Log in',
  courses: 'Courses',
  coursesOffered: 'Our courses',
  noCoursesAvailable:
    'It seems that there are currently no courses on offer, please check back later.',
  signUpToCourse: 'Sign up',
  capacity: 'Capacity',
  languageLevel: 'Level',
  enrollInCourse: 'Enroll',
  cancelEnrollment: 'Cancel enrollment',
  courseFull: 'Course is full',
  teacher: 'Teacher',
  addNewCourse: 'Add new course',
  courseName: 'Course name',
  courseDescription: 'Course description',
  courseLanguage: 'Course language',
  price: 'Price',
  myCourses: 'My courses',
  noUserCourses: "You aren't enrolled in any courses.",
  groupChat: 'Group chat',
};
