export default {
  home: 'Home',
  about: 'About',
  registration: 'Sign up',
  login: 'Log in',
  logout: 'Logout',
  courses: 'Courses',
  coursesOffered: 'Our courses',
  noCoursesAvailable:
    'It seems that there are currently no courses on offer, please check back later.',
  signUpToCourse: 'Sign up',
  capacity: 'Capacity',
  languageLevel: 'Level',
  enrollInCourse: 'Enroll',
  cancelEnrollment: 'Cancel enrollment',
  courseFull: 'Course is full',
  teacher: 'Teacher',
  addNewCourse: 'Add new course',
  courseName: 'Course name',
  courseDescription: 'Course description',
  courseLanguage: 'Course language',
  price: 'Price',
  myCourses: 'My courses',
  noUserCourses: "You aren't enrolled in any courses.",
  groupChat: 'Group chat',
  profilePicture: 'Profile picture',
  profile: 'Profile',
  registration_failure: 'Registration has failed.',
  registration_success_title: 'Successful registration!',
  registration_success_msg: 'Registration was successful.',
  login_failure: 'Login has failed.',
  login_success: 'Login was successful.',
  first_name_field_required: 'First name field is required',
  last_name_field_required: 'Last name field is required',
  email_field_required: 'Email field is required',
  password_field_required: 'Password field is required',
  invalid_email_format: 'Invalid email format',
  invalid_length_password: 'Password must be at least 8 characters long',
  passwords_must_match: 'Passwords must match',
  no_account_yet: "Don't have an account yet?",
  register_yourself: 'Sign up!',
  or_uppercase: 'OR',
  sign_in_with: 'Sign in with ',
  register_for_language_school: 'Register for a language school!',
  take_language_skills_to_next_level:
    'And take your language skills to a new level!',
  reset: 'Reset',
  already_have_account: 'Already have an accout?',
  login_yourself: 'Log in!',
  welcome_home_screen: 'Welcome to the home page of LangIS application!',
  home_screen_msg:
    'Choose the current course offer from the menu above or view your currently registered courses.',
  are_you_sure: 'Are you sure?',
  replace_profile_picture:
    'Are you sure you want to change your profile picture to the selected picture?',
  submit: 'Submit',
  profile_picture_change_success:
    'Profile photo has been successfully changed! You must refresh the page to see the changes!',
  profile_picture_change_failure: 'Profile photo upload has failed!',
  not_listed: 'Not listed',
  information: 'Information: ',
  email: 'Email: ',
  role: 'Role: ',
  age: 'Age: ',
  location: 'Location: ',
  page_not_found: 'Page not found!',
  page_not_found_msg:
    'The page you are looking for might have been removed, hat its name changed or is temporalily unavailable.',
  go_to_homepage: 'Go to Homepage',
  enter_your_email: 'Enter your email...',
  password: 'Password: ',
  enter_your_password: 'Enter your password...',
  first_name: 'First name: ',
  enter_your_first_name: 'Enter your first name...',
  last_name: 'Last name: ',
  enter_your_last_name: 'Enter your last name...',
  confirm_password: 'Confirmation of password: ',
  enter_your_confirmation_password: 'Enter your password again...',
  beginner: 'Beginner',
  elemenatary: 'Elementary',
  preIntermediate: 'Pre-Intermediate',
  intermediate: 'Intermediate',
  upperIntermediate: 'Upper-Intermediate',
  advanced: 'Advanced',
  english: 'English',
  spanish: 'Spanish',
  italian: 'Italian',
  german: 'German',
  french: 'French',
  courseDetail: 'Course detail',
  courseAddedSuccessfullyTitle: 'Course created!',
  courseAddedSuccessfullyMsg: 'The new course has been successfully added.',
  courseAddedFailed: 'Error - course has not been created!',
  edit: 'Edit',
  delete: 'Delete',
  noLessonsAvailable: 'This course has no lessons at the moment',
  lesson: 'Lesson',
  minutes: 'minutes',
  classroom: 'Classroom',
  lessonContent: 'Lesson content',
  averageRating: 'Average rating',
  noRating: 'No rating yet',
};
