export default {
  home: 'Domov',
  about: 'O nás',
  registration: 'Registrácia',
  login: 'Prihlásenie',
  logout: 'Odhlásenie',
  courses: 'Kurzy',
  coursesOffered: 'Naše kurzy',
  noCoursesAvailable: 'Zdá sa, že momentálne nie sú v ponuke žiadne kurzy.',
  signUpToCourse: 'Prihlásiť sa',
  capacity: 'Kapacita',
  languageLevel: 'Úroveň',
  enrollInCourse: 'Zapísať  sa',
  cancelEnrollment: 'Zrušiť zápis',
  courseFull: 'Kurz je naplno obsadený',
  teacher: 'Učiteľ',
  addNewCourse: 'Pridať nový kurz',
  courseName: 'Názov kurzu',
  courseDescription: 'Popis kurzu',
  courseLanguage: 'Jazyk kurzu',
  price: 'Cena',
  myCourses: 'Moje kurzy',
  noUserCourses: 'Nie ste zapísaní v žiadnom kurze.',
  groupChat: 'Skupinový chat',
  profilePicture: 'Profilová fotka',
  profile: 'Profil',
  registration_failure: 'Registrácia nebola úspešná.',
  registration_success_title: 'Úspešná registrácia!',
  registration_success_msg: 'Registrácia prebehla úspešne.',
  login_failure: 'Prihlásenie nebolo úspešné.',
  login_success: 'Prihlásenie bolo úspešné.',
  first_name_field_required: 'Pole krstného mena je povinné',
  last_name_field_required: 'Pole priezviska je povinné',
  email_field_required: 'Pole pre email je povinné',
  password_field_required: 'Pole pre heslo je povinné',
  invalid_email_format: 'Neplatný formát e-mailu',
  invalid_length_password: 'Heslo musí mať aspoň 8 znakov',
  passwords_must_match: 'Heslá sa musia zhodovať',
  no_account_yet: 'Ešte nemáte účet?',
  register_yourself: 'Zaregistrujte sa!',
  or_uppercase: 'ALEBO',
  sign_in_with: 'Prihlásiť sa skrz ',
  register_for_language_school: 'Zaregistrujte sa do jazykovej školy!',
  take_language_skills_to_next_level:
    'A posuňte svoje jazykové znalosti na novú úroveň!',
  reset: 'Resetovať',
  already_have_account: 'Už máte účet?',
  login_yourself: 'Prihláste sa!',
  welcome_home_screen: 'Vitajte na domovskej stránke aplikácie LangIS!',
  home_screen_msg:
    'Z ponuky vyššie si vyberte aktuálnu ponuku kurzov alebo si prehliadnite vaše aktuálne zaregistrované kurzy.',
  are_you_sure: 'Ste si istý?',
  replace_profile_picture:
    'Opravdu chcete zmeniť vašu profilovú fotku za vybranú fotku?',
  submit: 'Potvrdiť',
  profile_picture_change_success:
    'Profilová fotka bola úspešne zmenena! Pre zobrazenie zmien je nutné refreshnúť stránku!',
  profile_picture_change_failure: 'Odovzdanie vašej profilovej fotky zlyhalo!',
  not_listed: 'Neuvedené',
  information: 'Informácie: ',
  email: 'Email: ',
  role: 'Roľa: ',
  age: 'Vek: ',
  location: 'Lokácia: ',
  page_not_found: 'Stránka sa nenašla!',
  page_not_found_msg:
    'Stránka, ktorú hľadáte, mohla byť odstránená, zmenil sa jej názov alebo je dočasne nedostupná.',
  go_to_homepage: 'Prejsť na domovskú stránku',
  enter_your_email: 'Zadajte svoj email...',
  password: 'Heslo: ',
  enter_your_password: 'Zadajte svoje heslo...',
  first_name: 'Krstné meno: ',
  enter_your_first_name: 'Zadajte svoje krstné meno...',
  last_name: 'Priezvisko: ',
  enter_your_last_name: 'Zadajte svoje priezvisko...',
  confirm_password: 'Potvrdenie hesla: ',
  enter_your_confirmation_password: 'Znova zadajte svoje heslo...',
  beginner: 'Úplný začiatočník',
  elemenatary: 'Začiatočníci',
  preIntermediate: 'Mierne pokročilí',
  intermediate: 'Stredne pokročilí',
  upperIntermediate: 'Vyššie pokročilí',
  advanced: 'Pokročilí',
  english: 'Angličtina',
  spanish: 'Španielčina',
  italian: 'Taliančina',
  german: 'Němčina',
  french: 'Francúzština',
  courseDetail: 'Detail kurzu',
  courseAddedSuccessfullyTitle: 'Kurz bol vytvorený!',
  courseAddedSuccessfullyMsg: 'Nový kurz bol úspešne pridaný.',
  courseAddedFailed: 'Chyba - kurz nebol pridaný!',
  edit: 'Upraviť',
  delete: 'Zmazať',
  noLessonsAvailable: 'Tento kurz nemá aktuálne žiadne lekcie',
  lesson: 'Lekcia',
  minutes: 'minút',
  classroom: 'Učebňa',
  lessonContent: 'Náplň lekcie',
  averageRating: 'Priemerné hodnotenie',
  noRating: 'Zatím bez hodnotenia',
  addNewLesson: 'Pridať novú lekciu',
  rateThisCourse: 'Ohodnoťte tento kurz!',
  cancel: 'Zrušit',
  rate: 'Ohodnotiť!',
  lessonLengthInMinutes: 'Dĺžka v minútach',
  lessonDateAndTime: 'Datum a čas',
  deleteLesson: 'Zmazať lekciu',
  deleteFile: 'Zmazať súbor',
  uploadFile: 'Nahrať súbor',
  fileIsRequired: 'Súbor je povinný!',
};
