export default {
  home: 'Domov',
  about: 'O nás',
  registration: 'Registrácia',
  login: 'Prihlásenie',
  courses: 'Kurzy',
  coursesOffered: 'Our courses',
  noCoursesAvailable: 'It seems that there are currently no courses on offer.',
  signUpToCourse: 'Sign up',
  capacity: 'Capacity',
  languageLevel: 'Language level',
  enrollInCourse: 'Enroll',
  cancelEnrollment: 'Cancel enrollment',
  courseFull: 'Course is full',
  teacher: 'Teacher',
};
